name: Android Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web app
        run: npm run build
      
      - name: Copy web assets to Android
        run: npx cap copy android
      
      - name: Sync Android project
        run: npx cap sync android
      
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
      
      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug
      
      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease
        
      - name: Build Release AAB (Android App Bundle)
        run: cd android && ./gradlew bundleRelease
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
      
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          
      - name: Upload Release AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab