name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web app
        run: npm run build
      
      - name: Copy web assets to iOS
        run: npx cap copy ios
      
      - name: Sync iOS project
        run: npx cap sync ios
      
      - name: Install CocoaPods dependencies
        run: cd ios/App && pod install
      
      - name: Build iOS app
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Debug -derivedDataPath build
      
      - name: Archive iOS app output
        run: |
          cd ios/App
          mkdir -p Artifacts
          cp -r build/Build/Products/Debug-iphonesimulator/App.app Artifacts/
      
      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-debug-build
          path: ios/App/Artifacts